### ISSUE TITLE
NMES 1987 Replication Dataset

### ISSUE THREAD

**Issue by jakedailey1** [jaredsmurray/bcf#17]
Hello! Could you please add the NMES dataset you used in Hahn, Murray and Carvalho (2017) to this repository (or a link therein)? This seems to be the go-to benchmark for the continuous treatment, continuous outcome problem domain and yet it is not straightforward to translate the original, public files into a modern (e.g. CSV) file format. Thanks in advance!

**Comment by jaredsmurray** [comment]
The data are available in the TriMatch packge as nmes
