### ISSUE TITLE
Implementation of binary outcome

### ISSUE THREAD

**Issue by arnaudfrn** [jaredsmurray/bcf#2]
Thanks so much for the work ! 
I read here (https://rdrr.io/cran/bcf/) that the bcf currently only works with continous outcomes. Any plans for an implementation for binary outcomes ? 

Happy to work on a pull request if it can be easily implemented in R

**Comment by jaredsmurray** [comment]
Strictly speaking the implementation isn't difficult, but the interpretation is (tau is no longer the treatment effect on the outcome scale, but on a latent scale). While it's still a reasonable model it's difficult to calibrate by default, so it doesn't appear in this package right now.
