### ISSUE TITLE
Is there any reason to comment out 'mu' element output??

### ISSUE THREAD

**Issue by tmitanitky** [jaredsmurray/bcf#3]
Thank you for a great paper and implementation. 

I got trouble in visualizing tau and mu separately.

I couldn't get ```mu``` output from ```bcf_fit = bcf(y, z, x, x, pihat, nburn=2000, nsim=2000)``` to find the line 284 in bcf is commented out.
Is there any reason for the comment out line 284 in bcf.R?

https://rdrr.io/cran/bcf/man/bcf.html tells bcf return ```mu```, but the explanation for ```mu``` would be "nsim by n matrix of posterior samples of  prognostic scores".

https://github.com/jaredsmurray/bcf/blob/cb5dcfc9b611dcf721ed09bdca88ff6c152946e1/R/bcf.R#L282-L289

**Comment by jaredsmurray** [comment]
mu as commented out would be on a strange scale. The prognostic score E(Y|z=0, x=0) is given by yhat if the observation has z=0 or yhat - tau if the observation has z=1.
